name: Trigger auto deployment for weatherapp

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'frontend/**'
    - '.github/workflows/weatherapp-AutoDeployTrigger-b88e1e50-a14f-4de2-964c-76997baa3b08.yml'

  # Allow mannually trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.WEATHERAPP_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}/frontend 
          registryUrl: pzuchowski000.azurecr.io
          registryUsername: ${{ secrets.WEATHERAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.WEATHERAPP_REGISTRY_PASSWORD }}
          containerAppName: weatherapp
          resourceGroup: weatherapp
          imageToBuild: pzuchowski000.azurecr.io/weatherapp:${{ github.sha }}
          dockerfilePath: Dockerfile

     

